### ISSUE TITLE
New GL Time Tables

### ISSUE THREAD

**Issue by MelekElloumi** [wadhah101/insat-gl-knowledge#28]
In this [Gdrive](https://drive.google.com/drive/folders/1wv1BRVHptO2yeV9yIBHHcfqaGOc1Mfbn?usp=share_link) you'll find time tables with the new subjects from GL2 to GL5.
Some subjects have been changed from GL4 to GL3.
These are for the first semester only. We still don't know the new subject organisation in the second semester.
The docs of each subject may have to be reorganized in the future.

**Comment by wadhah101** [comment]
This will work better archived as it's not an active in development issue
