### ISSUE TITLE
Optimize images at repository for better storage

### ISSUE THREAD

**Issue by wadhah101** [wadhah101/insat-gl-knowledge#35]
- Add script to convert images to webp with 85% quality, replace suffixes. use **imagemagick** cli 
- Add a script to clean githistory from old images to save on git space

**Comment by wadhah101** [comment]
Make script to upload image to azure blob container regularly  with max compression and then auto link images.

**Comment by wadhah101** [comment]
@Mellywins  Let's keep communication here

**Comment by Mellywins** [comment]
will take this

**Comment by wadhah101** [comment]
ASSIGNED to @Mellywins

**Comment by wadhah101** [comment]
gentle nudges about this :eyes:
