### ISSUE TITLE
Port GL3/Complexity/cheat-sheet from notion to markdown

### ISSUE THREAD

**Issue by wadhah101** [wadhah101/insat-gl-knowledge#37]
same for Design GL3/Pattern/cheat-sheet

Notion can perfectly export its content to Markddown with proper asset folder for images. this issue shouldn't be hard
Contact the Notion pages owner and ask them for markdown export.

You can probably export full workspace with one click <https://www.notion.so/help/export-your-content#export-your-entire-workspace>

**Comment by wadhah101** [comment]
@rihemebh  Interested ?

**Comment by rihemebh** [comment]
Okay I'll do it

**Comment by wadhah101** [comment]
@rihemebh 
Thank you ☺️

**Comment by rihemebh** [comment]
@wadhah101 check PR

**Comment by wadhah101** [comment]
@rihemebh Great job
Merged and formatted
